---
# name: Clone homesick
# name: Pull dotfiles into homesic
# name: Stash dotfiles

- name: Add homeshick
  git:
    repo: "https://github.com/andsens/homeshick.git"
    dest: $HOME/.homesick/repos/homeshick
    version: master
    track_submodules: true
    accept_hostkey: true
    ssh_opts: -o StrictHostKeyChecking=no

- name: Clone dotfiles files using homesick
  command: ./homeshick clone "https://github.com/ylogx/dotfiles.git"
  args:
    chdir: ~/.homesick/repos/homeshick/bin
    creates: ~/.homesick/repos/dotfiles

- name: Link files using homesick
  command: ./homeshick link --force
  args:
    chdir: ~/.homesick/repos/homeshick/bin

- name: Pull latest dotfiles files using homesick
  command: ./homeshick pull dotfiles
  args:
    chdir: ~/.homesick/repos/homeshick/bin
# name: Pop Stash
