---
# name: Clone homesick
# name: Pull dotfiles into homesic
# name: Stash dotfiles

- name: Add homeshick
  become: false
  git:
    repo: "https://github.com/andsens/homeshick.git"
    dest: $HOME/.homesick/repos/homeshick
    version: master
    track_submodules: yes
    accept_hostkey: yes
    ssh_opts: -o StrictHostKeyChecking=no

- name: Clone dotfiles files using homesick
  become: false
  command: ./homeshick clone https://github.com/ylogx/dotfiles.git
  args:
    chdir: ~/.homesick/repos/homeshick/bin
    creates: ~/.homesick/repos/dotfiles

- name: Link files using homesick
  become: false
  command: ./homeshick link --force
  when: true
  args:
    chdir: ~/.homesick/repos/homeshick/bin

- name: Pull latest dotfiles files using homesick
  become: false
  command: ./homeshick pull dotfiles
  when: true
  args:
    chdir: ~/.homesick/repos/homeshick/bin
# name: Pop Stash
