---
#- name: Update packages
#  become: yes
#  apt: upgrade=dist update_cache=yes
#  tags: package

- name: Install libraries using package manager
  become: true
  become_method: sudo
  package:
    state: present
    name:
      #- ack-grep  # Unavailable on ubuntu 17.10
      - bash
      - curl
      - git
      - highlight
      - htop
      - nmap
      - python3
      - tmux
      - tree
      - vim
      - wget
      - zsh
  tags: package

- name: Install libraries using package manager that might not be available
  become: true
  become_method: sudo
  package:
    state: present
    name:
      - bat
      - exa
      - hexyl
  ignore_errors: true
  tags: package

- name: Install libraries using package manager that unlikely to be available
  become: true
  become_method: sudo
  package:
    state: present
    name: "{{ item }}"
  with_items:
    #- binocle # cargo install binocle
    - diskus
    - fd
  ignore_errors: true
  tags: package
