---
- name: "Current screenshots location"
  command: defaults read com.apple.screencapture location
  register: screenshot_location

- name: "Save screenshots to Pictures"
  command: defaults write com.apple.screencapture location ~/Pictures/
  # when: screenshot_location != ~/Pictures/
  tags: settings

- name: "Show hidden files in Finder"
  command: defaults write com.apple.finder AppleShowAllFiles TRUE
  tags: settings

- name: "Restart all Finder windows"
  command: killall Finder
  tags: settings
  # TODO: Only perform if previous command makes changes
