---
- name: Create screenshots folder
  file:
    path: "~/Pictures/ScreenShots"
    state: directory
  register: screenshots_folder
  tags: settings

- name: "Save screenshots to Pictures"
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "{{ screenshots_folder.path }}"
    state: present
  tags: settings

- name: "Show hidden files in Finder"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
    state: present
  register: settings_hidden_file_changes
  tags: settings

- name: "Restart all Finder windows"
  command: "killall Finder"
  when: settings_hidden_file_changes.changed
  tags: settings
